const products = [
    {
        id: 1,
        package: 'singles',
        header: 'Transfer Factor',
        sub_header: 'Tri Factor Plus',
        img: '/products/singles/tf-trifactor-plus.png',
        type: 'transfer-factor',
        side: 'TRANSFER FACTOR',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 801 k',
        price_amnt_2: 'Rp 1.065 k',
    },
    {
        id: 2,
        package: 'singles',
        header: 'Transfer Factor',
        sub_header: 'Tri Factor',
        img: '/products/singles/tf-trifactor.png',
        type: 'transfer-factor',
        side: 'TRANSFER FACTOR',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 560 k',
        price_amnt_2: 'Rp 746 k',
    },
    {
        id: 3,
        package: 'singles',
        header: 'Transfer Factor',
        sub_header: 'Chewable',
        img: '/products/singles/tf-chewable.png',
        type: 'transfer-factor',
        side: 'TRANSFER FACTOR',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 575 k',
        price_amnt_2: 'Rp 765 k',
    },
    {
        id: 4,
        package: 'singles',
        header: 'Transfer Factor',
        sub_header: 'Topical Gel',
        img: '/products/singles/tf-tropical-gel.png',
        type: 'transfer-factor',
        side: 'TRANSFER FACTOR',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 300 k',
        price_amnt_2: 'Rp 399 k',
    },
    {
        id: 5,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Belle Vie',
        img: '/products/singles/targeted-bellevie.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 640 k',
        price_amnt_2: 'Rp 852 k',
    },
    {
        id: 6,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'CV',
        img: '/products/singles/targeted-cv.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 368 k',
        price_amnt_2: 'Rp 490 k',
    },
    {
        id: 7,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Glucoach',
        img: '/products/singles/targeted-glucoach.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 368 k',
        price_amnt_2: 'Rp 490 k',
    },
    {
        id: 8,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Recall',
        img: '/products/singles/targeted-recall.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 680 k',
        price_amnt_2: 'Rp 904 k',
    },
    {
        id: 9,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Vista',
        img: '/products/singles/targeted-vista.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 675 k',
        price_amnt_2: 'Rp 898 k',
    },
    {
        id: 10,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Vitamin',
        img: '/products/singles/targeted-vitamin.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 368 k',
        price_amnt_2: 'Rp 490 k',
    },
    {
        id: 11,
        package: 'singles',
        header: 'Transform',
        sub_header: 'PRO-TF',
        img: '/products/singles/transform-pro.png',
        type: 'transform',
        side: 'TRANSFORM',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 990 k',
        price_amnt_2: 'Rp 1.316 k',
    },
    {
        id: 12,
        package: 'singles',
        header: 'Transform',
        sub_header: 'Renuvo',
        img: '/products/singles/transform-renuvo.png',
        type: 'transform',
        side: 'TRANSFORM',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 700 k',
        price_amnt_2: 'Rp 931 k',
    },
    {
        id: 13,
        package: 'singles',
        header: 'ShapeRite',
        sub_header: 'Nutrastart',
        img: '/products/singles/shaperite-nutrastart.png',
        type: 'shaperite',
        side: 'SHAPERITE',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 514 k',
        price_amnt_2: 'Rp 684 k',
    },
    {
        id: 14,
        package: 'singles',
        header: 'Wellness',
        sub_header: 'PBGS+',
        img: '/products/singles/wellness-pbgs.png',
        type: 'wellness',
        side: 'BASIC WELLNESS',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 415 k',
        price_amnt_2: 'Rp 552 k',
    },
    {
        id: 15,
        package: 'boxes',
        header: 'Riovida',
        sub_header: '2xBotol 500ml',
        img: '/products/boxes/riovida.png',
        type: 'riovida',
        side: 'RIOVIDA',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 861 k',
        price_amnt_2: 'Rp 1.145 k',
    },
    {
        id: 16,
        package: 'boxes',
        header: 'Riovida',
        sub_header: '1xBotol 500ml',
        img: '/products/boxes/riovida.png',
        type: 'riovida',
        side: 'RIOVIDA',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 441 k',
        price_amnt_2: 'Rp 587 k',
    },
    {
        id: 17,
        package: 'boxes',
        header: 'Riovida',
        sub_header: 'Burst',
        img: '/products/boxes/riovida-burst.png',
        type: 'riovida',
        side: 'RIOVIDA',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 493 k',
        price_amnt_2: 'Rp 656 k',
    },
    {
        id: 18,
        package: 'boxes',
        header: 'Digest',
        sub_header: 'Tea4Life',
        img: '/products/boxes/digest-tea.png',
        type: 'digest',
        side: 'DIGEST',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 234 k',
        price_amnt_2: 'Rp 311 k',
    },
    {
        id: 19,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Business 1',
        img: '/products/packs/business-1.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 4.730 k',
        price_amnt_2: '-',
    },
    {
        id: 20,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Business 2',
        img: '/products/packs/business-2.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Paket',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 4.544 k',
        price_amnt_2: 'Rp 2.104 k',
    },
    {
        id: 21,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Personal 1',
        img: '/products/packs/personal-1.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 2.875 k',
        price_amnt_2: '-',
    },
    {
        id: 22,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Personal 2',
        img: '/products/packs/personal-2.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Paket',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 2.909 k',
        price_amnt_2: 'Rp 1.346 k',
    },
    {
        id: 23,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Personal Basic',
        img: '/products/packs/personal-basic.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 2.542 k',
        price_amnt_2: '-',
    },
    {
        id: 24,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Personal Plus',
        img: '/products/packs/personal-plus.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 2.700 k',
        price_amnt_2: '-',
    },
    {
        id: 25,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Recall Launch',
        img: '/products/packs/recall-launch.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 2.027 k',
        price_amnt_2: 'Rp 938 k',
    },
    {
        id: 26,
        package: 'packs',
        header: 'Paket',
        sub_header: 'CV & Vitamin',
        img: '/products/packs/cv-vitamin.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 710 k',
        price_amnt_2: 'Rp 944 k',
    },
    {
        id: 27,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Glucoach & Vitamin',
        img: '/products/packs/vitamin-glucoach.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Member',
        price_desc_2: 'Non Member',
        price_amnt_1: 'Rp 710 k',
        price_amnt_2: 'Rp 944 k',
    }
]
    

export default products