const products = [
    {
        id: 1,
        package: 'singles',
        header: 'Transfer Factor',
        sub_header: 'Tri Factor Plus',
        img: '/products/singles/tf-trifactor-plus.png',
        type: 'transfer-factor',
        side: 'TRANSFER FACTOR',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 728 k',
        price_amnt_2: 'Rp 336 k',
    },
    {
        id: 2,
        package: 'singles',
        header: 'Transfer Factor',
        sub_header: 'Tri Factor',
        img: '/products/singles/tf-trifactor.png',
        type: 'transfer-factor',
        side: 'TRANSFER FACTOR',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 509 k',
        price_amnt_2: 'Rp 236 k',
    },
    {
        id: 3,
        package: 'singles',
        header: 'Transfer Factor',
        sub_header: 'Chewable',
        img: '/products/singles/tf-chewable.png',
        type: 'transfer-factor',
        side: 'TRANSFER FACTOR',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 522 k',
        price_amnt_2: 'Rp 242 k',
    },
    {
        id: 4,
        package: 'singles',
        header: 'Transfer Factor',
        sub_header: 'Tropical Gel',
        img: '/products/singles/tf-tropical-gel.png',
        type: 'transfer-factor',
        side: 'TRANSFER FACTOR',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 272 k',
        price_amnt_2: 'Rp 126 k',
    },
    {
        id: 5,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Bellevie',
        img: '/products/singles/targeted-bellevie.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 582 k',
        price_amnt_2: 'Rp 269 k',
    },
    {
        id: 6,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'CV',
        img: '/products/singles/targeted-cv.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 335 k',
        price_amnt_2: 'Rp 155 k',
    },
    {
        id: 7,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Glucoach',
        img: '/products/singles/targeted-glucoach.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 335 k',
        price_amnt_2: 'Rp 155 k',
    },
    {
        id: 8,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Recall',
        img: '/products/singles/targeted-recall.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 618 k',
        price_amnt_2: 'Rp 285 k',
    },
    {
        id: 9,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Vista',
        img: '/products/singles/targeted-vista.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 613 k',
        price_amnt_2: 'Rp 284 k',
    },
    {
        id: 10,
        package: 'singles',
        header: 'TF - Targeted',
        sub_header: 'Vitamin',
        img: '/products/singles/targeted-vitamin.png',
        type: 'tf-targeted',
        side: 'TF - TARGETED',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 335 k',
        price_amnt_2: 'Rp 155 k',
    },
    {
        id: 11,
        package: 'singles',
        header: 'Transform',
        sub_header: 'PRO-TF',
        img: '/products/singles/transform-pro.png',
        type: 'transform',
        side: 'TRANSFORM',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 990 k',
        price_amnt_2: 'Rp 1.316 k',
    },
    {
        id: 12,
        package: 'singles',
        header: 'Transform',
        sub_header: 'Renuvo',
        img: '/products/singles/transform-renuvo.png',
        type: 'transform',
        side: 'TRANSFORM',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 636 k',
        price_amnt_2: 'Rp 294 k',
    },
    {
        id: 13,
        package: 'singles',
        header: 'ShapeRite',
        sub_header: 'Nutrastart',
        img: '/products/singles/shaperite-nutrastart.png',
        type: 'shaperite',
        side: 'SHAPERITE',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 467 k',
        price_amnt_2: 'Rp 216 k',
    },
    {
        id: 14,
        package: 'singles',
        header: 'Wellness',
        sub_header: 'PBGS+',
        img: '/products/singles/wellness-pbgs.png',
        type: 'wellness',
        side: 'BASIC WELLNESS',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 377 k',
        price_amnt_2: 'Rp 147 k',
    },
    {
        id: 15,
        package: 'boxes',
        header: 'Riovida',
        sub_header: '',
        img: '/products/boxes/riovida.png',
        type: 'riovida',
        side: 'RIOVIDA',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 782 k',
        price_amnt_2: 'Rp 362 k',
    },
    {
        id: 16,
        package: 'boxes',
        header: 'Riovida',
        sub_header: 'Stix',
        img: '/products/boxes/riovida-stix.png',
        type: 'riovida',
        side: 'RIOVIDA',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 340 k',
        price_amnt_2: 'Rp 157 k',
    },
    {
        id: 17,
        package: 'boxes',
        header: 'Riovida',
        sub_header: 'Burst',
        img: '/products/boxes/riovida-burst.png',
        type: 'riovida',
        side: 'RIOVIDA',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 448 k',
        price_amnt_2: 'Rp 207 k',
    },
    {
        id: 18,
        package: 'boxes',
        header: 'Digest',
        sub_header: 'Tea4Life',
        img: '/products/boxes/digest-tea.png',
        type: 'digest',
        side: 'DIGEST',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 212 k',
        price_amnt_2: 'Rp 98 k',
    },
    {
        id: 19,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Business 1',
        img: '/products/packs/business-1.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 4.300 k',
        price_amnt_2: 'Rp 1.991 k',
    },
    {
        id: 20,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Business 2',
        img: '/products/packs/business-2.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 4.544 k',
        price_amnt_2: 'Rp 2.104 k',
    },
    {
        id: 21,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Personal 1',
        img: '/products/packs/personal-1.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 2.613 k',
        price_amnt_2: 'Rp 1.210 k',
    },
    {
        id: 22,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Personal 2',
        img: '/products/packs/personal-2.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 2.909 k',
        price_amnt_2: 'Rp 1.346 k',
    },
    {
        id: 23,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Personal Basic',
        img: '/products/packs/personal-basic.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 2.310 k',
        price_amnt_2: 'Rp 1.070 k',
    },
    {
        id: 24,
        package: 'packs',
        header: 'Paket',
        sub_header: 'Personal Plus',
        img: '/products/packs/personal-plus.png',
        type: 'pack',
        side: 'PAKET',
        price_desc_1: 'Grosir',
        price_desc_2: 'Hemat',
        price_amnt_1: 'Rp 2.454 k',
        price_amnt_2: 'Rp 1.136 k',
    }
]

// Cancelled
    // 1. Recall Launch
    // {
    //     id: 25,
    //     package: 'packs',
    //     header: 'Paket',
    //     sub_header: 'Recall Launch',
    //     img: '/products/packs/recall-launch.png',
    //     type: 'pack',
    //     side: 'PAKET',
    //     price_desc_1: 'Member',
    //     price_desc_2: 'Non Member',
    //     price_amnt_1: 'Rp 2.027 k',
    //     price_amnt_2: 'Rp 938 k',
    // }

export default products